### ISSUE TITLE
[TRACKER] TURRPG1 ports to-do list

### ISSUE THREAD

**Issue by 0xC0ncord** [0xC0ncord/TURRPG2#1]
# General
- [ ] Subclasses

# Abilities
- [ ] Advanced Medic
- [ ] Advanced Artifacts
- [ ] Combo Monster Benefit
- [ ] Conjurer Necromancy
- [ ] Conjurer Awareness
- [x] Conjurer Vampire
- [ ] Defense Sentinel Armor
- [ ] Defense Sentinel Energy
- [ ] Defense Sentinel Healing
- [ ] Defense Sentinel Resupply
- [ ] Defense Sentinel Shields
- [ ] Drone Combat
- [ ] Drone Defense
- [ ] Drone Link
- [ ] Engineer Base Specialist
- [ ] Engineer Sentinel Specialist
- [ ] Engineer Turret Specialist
- [ ] Engineer Utility Specialist
- [ ] Engineer Vehicle Specialist
- [x] Healing Adrenaline
- [x] Healing After Effects
- [x] Healing Flames
- [ ] Healing Link
- [x] Medic Incantation
- [x] Medic Pledge
- [x] Metamorphosis
- [x] Metamorphosis Refund
- [ ] Metamorphosis Adrenal Reserve
- [x] Monster Damage Bonus
- [x] Monster Damage Reduction
- [ ] Monster Survival
- [x] Monster Ultima
- [x] Multi-Combo
- [x] Nullifying Cure
- [x] Shield Vampire
- [x] Summoner's Link

# Artifacts
- [x] Conjurer Size
- [ ] Enhanced Make Magic Weapon Bias
- [ ] Hourglass
- [x] Jukebox
- [x] Music Discs
- [ ] Lightning Spire
- [ ] Lightning Storm
- [ ] Medic Regen Charge
- [ ] Medic Spire
- [ ] Monster Command

# Magic Weapons
- [x] Chain Lightning
- [x] Experience
- [x] Flight
- [x] Meditation
- [x] Quad-shot
- [x] Sharpshooting
- [x] Superfluous

# Utilities
- [ ] Weapon Locker
- [ ] Teleporter
- [ ] Dispenser
