### ISSUE TITLE
[TRACKER] Ability icons

### ISSUE THREAD

**Issue by 0xC0ncord** [0xC0ncord/TURRPG2#2]
# Abilities Needing New Icons
- [ ] Advanced Medic
- [ ] Advanced Artifacts
- [ ] Combo Monster Benefit
- [ ] Conjurer Necromancy
- [ ] Conjurer Awareness
- [ ] Conjurer Vampire
- [ ] Defense Sentinel Armor
- [ ] Defense Sentinel Energy
- [ ] Defense Sentinel Healing
- [ ] Defense Sentinel Resupply
- [ ] Defense Sentinel Shields
- [ ] Drone Base
- [ ] Drone Combat
- [ ] Drone Defense
- [ ] Drone Link
- [ ] Engineer Base Specialist
- [ ] Engineer Sentinel Specialist
- [ ] Engineer Turret Specialist
- [ ] Engineer Utility Specialist
- [ ] Engineer Vehicle Specialist
- [ ] Healing Adrenaline
- [ ] Healing After Effects
- [ ] Healing Flames
- [ ] Healing Link
- [ ] Loaded Engineer
- [ ] Medic Incantation
- [ ] Medic Pledge
- [ ] Metamorphosis
- [ ] Metamorphosis Refund
- [ ] Metamorphosis Adrenal Reserve
- [ ] Monster Damage Bonus
- [ ] Monster Damage Reduction
- [ ] Monster Survival
- [ ] Monster Ultima
- [ ] Multi-Combo
- [ ] Shield Vampire
- [ ] Summoner's Link
